---
fixtures:
  repositories:
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.25.0'
    nsswitch:
      repo: 'https://github.com/trlinkin/puppet-nsswitch.git'
      ref: '2.2.0'
  symlinks:
    pam: "#{source_dir}"
